client_config_backend: file
client_config:
  client_id: "Edit Here"
  client_secret: "Edit Here"
  
redirect_uris: ["urn:ietf:wg:oauth:2.0:oob","http://localhost"]
save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive
    - https://www.googleapis.com/auth/drive.install